# 应用服务端口
server:
  port: 8080

spring:
  # web配置
  web:
    # 静态资源处理
    resources:
      # 启用默认静态资源处理，默认启用
      add-mappings: true
      cache:
        cachecontrol:
          # 缓存响应时间，单位秒
          max-age: 3600
      chain:
        # 资源链中启用缓存，默认启用
        cache: true
        # 启用资源链，默认禁用
        enabled: true
        # 启用压缩资源(gzip,brotli)解析,默认禁用
        compressed: true
      # 静态资源位置
      static-locations: classpath:/static/
  # thymeleaf配置
  thymeleaf:
    cache: false
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    # hikari连接池
    hikari:
      # 线程池名称
      pool-name: SecondKillHikariCP
      # 最小空闲数，当minimumIdle小于maximumPoolSize时有效，0表示空闲连接永远不会被移除
      minimum-idle: 5
      # 空闲超时时间ms，此处为30min
      idle-timeout: 1800000
      # 最大线程池数
      maximum-pool-size: 10
      # 自动提交
      auto-commit: true
      # 最大存活时间ms
      max-lifetime: 1800000
      # 连接建立超时时间 单位ms 默认30000
      connection-timeout: 30000
      # 连接测试查询语句
      connection-test-query: SELECT 1
  # redis配置
  redis:
    # 服务器地址
    host: 127.0.0.1
    # 登录密码
    password: redis
    # 服务端口
    port: 6379
    # 超时时间
    timeout: 10000ms
    # 库0
    database: 0
    # 客户端lettuce配置，类似jedis
    lettuce:
      # 连接池配置
      pool:
        # 最大连接数，默认8
        max-active: 1024
        # 最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5
  # RabbitMQ配置
  rabbitmq:
    # 服务器地址
    host: 127.0.0.1
    # 用户名
    username: rabbitmq
    # 密码
    password: rabbitmq
    # 虚拟主机
    virtual-host: /
    # 端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        # 消费者最大数量
        max-concurrency: 10
        #限制消费者每次只处理一条消息，处理完再继续下一条消息
        prefetch: 1
        #启动时是否默认启动容器，默认true
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        # 发布重试，默认false
        enabled: true
        # 重试时间 默认1000ms
        initial-interval: 1000
        # 重试最大次数，默认3次
        max-attempts: 3
        # 重试最大间隔时间，默认10000ms
        max-interval: 10000
        # 重试间隔的乘数。比如配2.0 第一次等10s，第二次等20s，第三次等40s
        multiplier: 1.0
# Mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.kinson.secondkill.domain

# log4j配置
logging:
  # log4j配置文件的位置
  config: classpath:log4j2.xml
  # 配置sql打印的路径
  level:
    com.kinson.secondkill.mapper: debug
